apiVersion: v1
kind: Service
metadata:
  name: myflaskapp
spec:
  type: {{ .Values.service.type }}
  selector:
    app: myflaskapp
  ports:
  - protocol: TCP
    port: {{ .Values.service.port }}
    targetPort: 5000
